version: 2
updates:
  # Ensure GitHub Actions are used in their latest version
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "monthly"

  # Strategy for composer dependencies
  - package-ecosystem: "composer"
    directory: "/"
    schedule:
      interval: "monthly"
    allow:
      - dependency-type: "direct"
    open-pull-requests-limit: 100
    versioning-strategy: "increase"
    groups:
      dev-dependencies:
        dependency-type: "development"
