language: php

env:
  - DB=mysql

before_script:
  - composer self-update
  - if [[ ${TRAVIS_PHP_VERSION:0:3} == "5.4" ]]; then sed -e "s|.*"consolidation/robo".*$||" -i composer.json && composer update; fi
  - composer install -o
#  - mysql -u root -e 'create database glpitest;'
#  - php tools/cliinstall.php --lang=en_US --db=glpitest --user=root --tests

script:
#  - mysql -u root -e 'select version();'
#  - phpunit --verbose
  - vendor/bin/phpcs -p --ignore=vendor --ignore=js --standard=vendor/glpi-project/coding-standard/GlpiStandard/ .

matrix:
  include:
    - php: 5.4
      addons:
        mariadb: 5.5
    - php: 5.5
      addons:
        mariadb: 5.5
#    - php: 5.6
#      addons:
#        mariadb: 5.5
#    - php: 5.6
#      addons:
#        mariadb: 10.0
    - php: 5.6
      addons:
        mariadb: 10.1
#    - php: 7.0
#      addons:
#        mariadb: 10.0
    - php: 7.0
      addons:
        mariadb: 10.1
#    - php: 7.1
#      addons:
#        mariadb: 10.0
    - php: 7.1
      addons:
        mariadb: 10.1
    - php: nightly
      addons:
        mariadb: 10.1
  allow_failures:
    - php: nightly

cache:
  directories:
    - $HOME/.composer/cache

#notifications:
#  irc:
#    channels:
#      - "irc.freenode.org#channel"
#    on_success: change
#    on_failure: always
#    use_notice: true
#    skip_join: true
